### ISSUE TITLE
превышена квота данных

### ISSUE THREAD

**Issue by tarleproton** [daniilak/russian-cadastral-numbers#1]
Привет , спасибо за проект! Хотел воспользоваться данными, но увы. 

 This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access
 
 csv файлы выгрузить не получится( Возможно они залиты где то ещё? Спасибо!

**Comment by daniilak** [comment]
Перезалил пока то, что сейчас есть

**Comment by tarleproton** [comment]
файл с кварталами в репозитории ссылается на lfs - Error downloading pkk_cadastral_kvartals.csv (b6778932bc814a596de3d6984acb97e282035e9fafc3c4acdc96317e45630653): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by daniilak** [comment]
> файл с кварталами в репозитории ссылается на lfs - Error downloading pkk_cadastral_kvartals.csv (b6778932bc814a596de3d6984acb97e282035e9fafc3c4acdc96317e45630653): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Перезалил

**Comment by tarleproton** [comment]
Спасибо тебе!
